/*
 * i18n PRÓPRIO do portal público de agendamento (/agendar/[slug]).
 *
 * §10.D do PLANO_AGENDAMENTO_PUBLICO.md: o i18n do dashboard (locales/*.json via
 * next-intl) resolve o idioma do localStorage do usuário LOGADO e NÃO lê ?lang=.
 * O portal é público (visitante sem sessão), então usa este dicionário próprio,
 * escolhido por ?lang= no servidor/cliente — mesma estratégia das páginas legais.
 * Datas/horas usam Intl (locale-aware), sem chaves aqui.
 */

export const BOOKING_LANGS = [
  "pt", "en", "es", "de", "fr", "it", "ja", "zh", "ar", "hi", "id", "ru", "tr"
] as const;

export type BookingLang = (typeof BOOKING_LANGS)[number];

export function resolveBookingLang(raw: string | string[] | undefined | null): BookingLang {
  const v = Array.isArray(raw) ? raw[0] : raw;
  return (BOOKING_LANGS as readonly string[]).includes(v || "") ? (v as BookingLang) : "pt";
}

export type BookingStrings = Record<string, string>;

const STRINGS: Record<BookingLang, BookingStrings> = {
  pt: {
    chooseService: "Escolha um serviço",
    chooseDate: "Escolha uma data",
    availableTimes: "Horários disponíveis",
    noSlots: "Nenhum horário disponível",
    noDays: "Nenhum horário disponível no momento",
    loading: "Carregando...",
    yourDetails: "Seus dados",
    nameLabel: "Nome",
    phoneLabel: "WhatsApp (com DDD)",
    emailLabel: "E-mail (opcional)",
    requiredField: "Campo obrigatório",
    confirmBtn: "Confirmar agendamento",
    booking: "Agendando...",
    back: "Voltar",
    confirmedTitle: "Agendamento confirmado!",
    confirmedDesc: "Você receberá a confirmação no WhatsApp.",
    newBooking: "Fazer outro agendamento",
    errSlot: "Esse horário não está mais disponível. Escolha outro.",
    errGeneric: "Não foi possível concluir. Tente novamente.",
    minLabel: "min",
    selectPlaceholder: "Selecione",
    notFound: "Página de agendamento não encontrada.",
    yourBooking: "Seu agendamento",
    cancelBtn: "Cancelar agendamento",
    rescheduleBtn: "Remarcar",
    cancelledMsg: "Seu agendamento foi cancelado.",
    rescheduledMsg: "Agendamento remarcado!",
    chooseNewTime: "Escolha um novo horário",
    cannotManage: "Este agendamento não pode mais ser alterado.",
    confirmCancel: "Tem certeza que deseja cancelar?",
    chooseProfessional: "Escolha um profissional",
    anyProfessional: "Qualquer um",
    seatsLeft: "Vagas: {n}"
  },
  en: {
    chooseService: "Choose a service",
    chooseDate: "Choose a date",
    availableTimes: "Available times",
    noSlots: "No times available",
    noDays: "No times available right now",
    loading: "Loading...",
    yourDetails: "Your details",
    nameLabel: "Name",
    phoneLabel: "WhatsApp (with area code)",
    emailLabel: "Email (optional)",
    requiredField: "Required field",
    confirmBtn: "Confirm booking",
    booking: "Booking...",
    back: "Back",
    confirmedTitle: "Booking confirmed!",
    confirmedDesc: "You will receive the confirmation on WhatsApp.",
    newBooking: "Make another booking",
    errSlot: "This time is no longer available. Please pick another.",
    errGeneric: "Could not complete. Please try again.",
    minLabel: "min",
    selectPlaceholder: "Select",
    notFound: "Booking page not found.",
    yourBooking: "Your booking",
    cancelBtn: "Cancel booking",
    rescheduleBtn: "Reschedule",
    cancelledMsg: "Your booking has been cancelled.",
    rescheduledMsg: "Booking rescheduled!",
    chooseNewTime: "Choose a new time",
    cannotManage: "This booking can no longer be changed.",
    confirmCancel: "Are you sure you want to cancel?",
    chooseProfessional: "Choose a professional",
    anyProfessional: "Anyone",
    seatsLeft: "Spots: {n}"
  },
  es: {
    chooseService: "Elige un servicio",
    chooseDate: "Elige una fecha",
    availableTimes: "Horarios disponibles",
    noSlots: "Sin horarios disponibles",
    noDays: "No hay horarios disponibles por ahora",
    loading: "Cargando...",
    yourDetails: "Tus datos",
    nameLabel: "Nombre",
    phoneLabel: "WhatsApp (con código de área)",
    emailLabel: "Correo (opcional)",
    requiredField: "Campo obligatorio",
    confirmBtn: "Confirmar reserva",
    booking: "Reservando...",
    back: "Volver",
    confirmedTitle: "¡Reserva confirmada!",
    confirmedDesc: "Recibirás la confirmación por WhatsApp.",
    newBooking: "Hacer otra reserva",
    errSlot: "Este horario ya no está disponible. Elige otro.",
    errGeneric: "No se pudo completar. Inténtalo de nuevo.",
    minLabel: "min",
    selectPlaceholder: "Selecciona",
    notFound: "Página de reservas no encontrada.",
    yourBooking: "Tu reserva",
    cancelBtn: "Cancelar reserva",
    rescheduleBtn: "Reprogramar",
    cancelledMsg: "Tu reserva ha sido cancelada.",
    rescheduledMsg: "¡Reserva reprogramada!",
    chooseNewTime: "Elige un nuevo horario",
    cannotManage: "Esta reserva ya no se puede modificar.",
    confirmCancel: "¿Seguro que deseas cancelar?",
    chooseProfessional: "Elige un profesional",
    anyProfessional: "Cualquiera",
    seatsLeft: "Cupos: {n}"
  },
  de: {
    chooseService: "Dienst wählen",
    chooseDate: "Datum wählen",
    availableTimes: "Verfügbare Zeiten",
    noSlots: "Keine Zeiten verfügbar",
    noDays: "Derzeit keine Zeiten verfügbar",
    loading: "Wird geladen...",
    yourDetails: "Ihre Daten",
    nameLabel: "Name",
    phoneLabel: "WhatsApp (mit Vorwahl)",
    emailLabel: "E-Mail (optional)",
    requiredField: "Pflichtfeld",
    confirmBtn: "Buchung bestätigen",
    booking: "Buchung läuft...",
    back: "Zurück",
    confirmedTitle: "Buchung bestätigt!",
    confirmedDesc: "Sie erhalten die Bestätigung per WhatsApp.",
    newBooking: "Weitere Buchung vornehmen",
    errSlot: "Diese Zeit ist nicht mehr verfügbar. Bitte wählen Sie eine andere.",
    errGeneric: "Konnte nicht abgeschlossen werden. Bitte erneut versuchen.",
    minLabel: "Min.",
    selectPlaceholder: "Auswählen",
    notFound: "Buchungsseite nicht gefunden.",
    yourBooking: "Ihre Buchung",
    cancelBtn: "Buchung stornieren",
    rescheduleBtn: "Verschieben",
    cancelledMsg: "Ihre Buchung wurde storniert.",
    rescheduledMsg: "Buchung verschoben!",
    chooseNewTime: "Neue Zeit wählen",
    cannotManage: "Diese Buchung kann nicht mehr geändert werden.",
    confirmCancel: "Möchten Sie wirklich stornieren?",
    chooseProfessional: "Wählen Sie eine Fachkraft",
    anyProfessional: "Beliebig",
    seatsLeft: "Plätze: {n}"
  },
  fr: {
    chooseService: "Choisissez un service",
    chooseDate: "Choisissez une date",
    availableTimes: "Horaires disponibles",
    noSlots: "Aucun horaire disponible",
    noDays: "Aucun horaire disponible pour le moment",
    loading: "Chargement...",
    yourDetails: "Vos coordonnées",
    nameLabel: "Nom",
    phoneLabel: "WhatsApp (avec indicatif)",
    emailLabel: "E-mail (facultatif)",
    requiredField: "Champ obligatoire",
    confirmBtn: "Confirmer la réservation",
    booking: "Réservation...",
    back: "Retour",
    confirmedTitle: "Réservation confirmée !",
    confirmedDesc: "Vous recevrez la confirmation sur WhatsApp.",
    newBooking: "Faire une autre réservation",
    errSlot: "Ce créneau n'est plus disponible. Veuillez en choisir un autre.",
    errGeneric: "Impossible de terminer. Veuillez réessayer.",
    minLabel: "min",
    selectPlaceholder: "Sélectionner",
    notFound: "Page de réservation introuvable.",
    yourBooking: "Votre réservation",
    cancelBtn: "Annuler la réservation",
    rescheduleBtn: "Reprogrammer",
    cancelledMsg: "Votre réservation a été annulée.",
    rescheduledMsg: "Réservation reprogrammée !",
    chooseNewTime: "Choisissez un nouveau créneau",
    cannotManage: "Cette réservation ne peut plus être modifiée.",
    confirmCancel: "Voulez-vous vraiment annuler ?",
    chooseProfessional: "Choisissez un professionnel",
    anyProfessional: "Peu importe",
    seatsLeft: "Places : {n}"
  },
  it: {
    chooseService: "Scegli un servizio",
    chooseDate: "Scegli una data",
    availableTimes: "Orari disponibili",
    noSlots: "Nessun orario disponibile",
    noDays: "Nessun orario disponibile al momento",
    loading: "Caricamento...",
    yourDetails: "I tuoi dati",
    nameLabel: "Nome",
    phoneLabel: "WhatsApp (con prefisso)",
    emailLabel: "E-mail (facoltativo)",
    requiredField: "Campo obbligatorio",
    confirmBtn: "Conferma prenotazione",
    booking: "Prenotazione...",
    back: "Indietro",
    confirmedTitle: "Prenotazione confermata!",
    confirmedDesc: "Riceverai la conferma su WhatsApp.",
    newBooking: "Effettua un'altra prenotazione",
    errSlot: "Questo orario non è più disponibile. Scegline un altro.",
    errGeneric: "Impossibile completare. Riprova.",
    minLabel: "min",
    selectPlaceholder: "Seleziona",
    notFound: "Pagina di prenotazione non trovata.",
    yourBooking: "La tua prenotazione",
    cancelBtn: "Annulla prenotazione",
    rescheduleBtn: "Riprogramma",
    cancelledMsg: "La tua prenotazione è stata annullata.",
    rescheduledMsg: "Prenotazione riprogrammata!",
    chooseNewTime: "Scegli un nuovo orario",
    cannotManage: "Questa prenotazione non può più essere modificata.",
    confirmCancel: "Sei sicuro di voler annullare?",
    chooseProfessional: "Scegli un professionista",
    anyProfessional: "Chiunque",
    seatsLeft: "Posti: {n}"
  },
  ja: {
    chooseService: "サービスを選択",
    chooseDate: "日付を選択",
    availableTimes: "予約可能な時間",
    noSlots: "予約可能な時間がありません",
    noDays: "現在予約可能な時間がありません",
    loading: "読み込み中...",
    yourDetails: "お客様情報",
    nameLabel: "名前",
    phoneLabel: "WhatsApp（市外局番付き）",
    emailLabel: "メール（任意）",
    requiredField: "必須項目",
    confirmBtn: "予約を確定",
    booking: "予約中...",
    back: "戻る",
    confirmedTitle: "予約が確定しました！",
    confirmedDesc: "確認はWhatsAppで届きます。",
    newBooking: "別の予約をする",
    errSlot: "この時間は予約できなくなりました。別の時間を選んでください。",
    errGeneric: "完了できませんでした。もう一度お試しください。",
    minLabel: "分",
    selectPlaceholder: "選択",
    notFound: "予約ページが見つかりません。",
    yourBooking: "ご予約",
    cancelBtn: "予約をキャンセル",
    rescheduleBtn: "予約を変更",
    cancelledMsg: "ご予約はキャンセルされました。",
    rescheduledMsg: "予約を変更しました！",
    chooseNewTime: "新しい時間を選択",
    cannotManage: "この予約は変更できません。",
    confirmCancel: "本当にキャンセルしますか？",
    chooseProfessional: "担当者を選択",
    anyProfessional: "指定なし",
    seatsLeft: "残り{n}枠"
  },
  zh: {
    chooseService: "选择服务",
    chooseDate: "选择日期",
    availableTimes: "可预约时间",
    noSlots: "暂无可预约时间",
    noDays: "目前暂无可预约时间",
    loading: "加载中...",
    yourDetails: "您的信息",
    nameLabel: "姓名",
    phoneLabel: "WhatsApp（含区号）",
    emailLabel: "邮箱（可选）",
    requiredField: "必填项",
    confirmBtn: "确认预约",
    booking: "预约中...",
    back: "返回",
    confirmedTitle: "预约已确认！",
    confirmedDesc: "您将通过 WhatsApp 收到确认。",
    newBooking: "再次预约",
    errSlot: "该时间已不可预约，请另选时间。",
    errGeneric: "无法完成，请重试。",
    minLabel: "分钟",
    selectPlaceholder: "请选择",
    notFound: "未找到预约页面。",
    yourBooking: "您的预约",
    cancelBtn: "取消预约",
    rescheduleBtn: "改期",
    cancelledMsg: "您的预约已取消。",
    rescheduledMsg: "预约已改期！",
    chooseNewTime: "选择新的时间",
    cannotManage: "该预约无法再修改。",
    confirmCancel: "确定要取消吗？",
    chooseProfessional: "选择服务人员",
    anyProfessional: "任意",
    seatsLeft: "剩余名额：{n}"
  },
  ar: {
    chooseService: "اختر خدمة",
    chooseDate: "اختر تاريخًا",
    availableTimes: "الأوقات المتاحة",
    noSlots: "لا توجد أوقات متاحة",
    noDays: "لا توجد أوقات متاحة حاليًا",
    loading: "جارٍ التحميل...",
    yourDetails: "بياناتك",
    nameLabel: "الاسم",
    phoneLabel: "WhatsApp (مع رمز المنطقة)",
    emailLabel: "البريد الإلكتروني (اختياري)",
    requiredField: "حقل إلزامي",
    confirmBtn: "تأكيد الحجز",
    booking: "جارٍ الحجز...",
    back: "رجوع",
    confirmedTitle: "تم تأكيد الحجز!",
    confirmedDesc: "ستتلقى التأكيد عبر WhatsApp.",
    newBooking: "إجراء حجز آخر",
    errSlot: "لم يعد هذا الوقت متاحًا. يرجى اختيار وقت آخر.",
    errGeneric: "تعذّر الإكمال. حاول مرة أخرى.",
    minLabel: "دقيقة",
    selectPlaceholder: "اختر",
    notFound: "صفحة الحجز غير موجودة.",
    yourBooking: "حجزك",
    cancelBtn: "إلغاء الحجز",
    rescheduleBtn: "إعادة الجدولة",
    cancelledMsg: "تم إلغاء حجزك.",
    rescheduledMsg: "تمت إعادة جدولة الحجز!",
    chooseNewTime: "اختر وقتًا جديدًا",
    cannotManage: "لم يعد من الممكن تغيير هذا الحجز.",
    confirmCancel: "هل أنت متأكد من الإلغاء؟",
    chooseProfessional: "اختر مختصًا",
    anyProfessional: "أي شخص",
    seatsLeft: "مقاعد: {n}"
  },
  hi: {
    chooseService: "एक सेवा चुनें",
    chooseDate: "एक तिथि चुनें",
    availableTimes: "उपलब्ध समय",
    noSlots: "कोई समय उपलब्ध नहीं",
    noDays: "अभी कोई समय उपलब्ध नहीं है",
    loading: "लोड हो रहा है...",
    yourDetails: "आपकी जानकारी",
    nameLabel: "नाम",
    phoneLabel: "WhatsApp (एरिया कोड सहित)",
    emailLabel: "ईमेल (वैकल्पिक)",
    requiredField: "आवश्यक फ़ील्ड",
    confirmBtn: "बुकिंग की पुष्टि करें",
    booking: "बुकिंग हो रही है...",
    back: "वापस",
    confirmedTitle: "बुकिंग की पुष्टि हो गई!",
    confirmedDesc: "आपको WhatsApp पर पुष्टि मिलेगी।",
    newBooking: "एक और बुकिंग करें",
    errSlot: "यह समय अब उपलब्ध नहीं है। कृपया दूसरा चुनें।",
    errGeneric: "पूरा नहीं हो सका। कृपया पुनः प्रयास करें।",
    minLabel: "मिनट",
    selectPlaceholder: "चुनें",
    notFound: "बुकिंग पेज नहीं मिला।",
    yourBooking: "आपकी बुकिंग",
    cancelBtn: "बुकिंग रद्द करें",
    rescheduleBtn: "पुनर्निर्धारित करें",
    cancelledMsg: "आपकी बुकिंग रद्द कर दी गई है।",
    rescheduledMsg: "बुकिंग पुनर्निर्धारित हुई!",
    chooseNewTime: "नया समय चुनें",
    cannotManage: "इस बुकिंग को अब बदला नहीं जा सकता।",
    confirmCancel: "क्या आप वाकई रद्द करना चाहते हैं?",
    chooseProfessional: "एक पेशेवर चुनें",
    anyProfessional: "कोई भी",
    seatsLeft: "स्थान: {n}"
  },
  id: {
    chooseService: "Pilih layanan",
    chooseDate: "Pilih tanggal",
    availableTimes: "Waktu tersedia",
    noSlots: "Tidak ada waktu tersedia",
    noDays: "Belum ada waktu tersedia saat ini",
    loading: "Memuat...",
    yourDetails: "Data Anda",
    nameLabel: "Nama",
    phoneLabel: "WhatsApp (dengan kode area)",
    emailLabel: "Email (opsional)",
    requiredField: "Wajib diisi",
    confirmBtn: "Konfirmasi pemesanan",
    booking: "Memesan...",
    back: "Kembali",
    confirmedTitle: "Pemesanan dikonfirmasi!",
    confirmedDesc: "Anda akan menerima konfirmasi di WhatsApp.",
    newBooking: "Buat pemesanan lain",
    errSlot: "Waktu ini sudah tidak tersedia. Silakan pilih yang lain.",
    errGeneric: "Tidak dapat menyelesaikan. Silakan coba lagi.",
    minLabel: "mnt",
    selectPlaceholder: "Pilih",
    notFound: "Halaman pemesanan tidak ditemukan.",
    yourBooking: "Pemesanan Anda",
    cancelBtn: "Batalkan pemesanan",
    rescheduleBtn: "Jadwalkan ulang",
    cancelledMsg: "Pemesanan Anda telah dibatalkan.",
    rescheduledMsg: "Pemesanan dijadwalkan ulang!",
    chooseNewTime: "Pilih waktu baru",
    cannotManage: "Pemesanan ini tidak dapat diubah lagi.",
    confirmCancel: "Yakin ingin membatalkan?",
    chooseProfessional: "Pilih profesional",
    anyProfessional: "Siapa saja",
    seatsLeft: "Sisa: {n}"
  },
  ru: {
    chooseService: "Выберите услугу",
    chooseDate: "Выберите дату",
    availableTimes: "Доступное время",
    noSlots: "Нет доступного времени",
    noDays: "Сейчас нет доступного времени",
    loading: "Загрузка...",
    yourDetails: "Ваши данные",
    nameLabel: "Имя",
    phoneLabel: "WhatsApp (с кодом города)",
    emailLabel: "Эл. почта (необязательно)",
    requiredField: "Обязательное поле",
    confirmBtn: "Подтвердить запись",
    booking: "Запись...",
    back: "Назад",
    confirmedTitle: "Запись подтверждена!",
    confirmedDesc: "Вы получите подтверждение в WhatsApp.",
    newBooking: "Сделать ещё одну запись",
    errSlot: "Это время больше недоступно. Выберите другое.",
    errGeneric: "Не удалось завершить. Попробуйте снова.",
    minLabel: "мин",
    selectPlaceholder: "Выберите",
    notFound: "Страница записи не найдена.",
    yourBooking: "Ваша запись",
    cancelBtn: "Отменить запись",
    rescheduleBtn: "Перенести",
    cancelledMsg: "Ваша запись отменена.",
    rescheduledMsg: "Запись перенесена!",
    chooseNewTime: "Выберите новое время",
    cannotManage: "Эту запись больше нельзя изменить.",
    confirmCancel: "Вы уверены, что хотите отменить?",
    chooseProfessional: "Выберите специалиста",
    anyProfessional: "Любой",
    seatsLeft: "Мест: {n}"
  },
  tr: {
    chooseService: "Bir hizmet seçin",
    chooseDate: "Bir tarih seçin",
    availableTimes: "Uygun saatler",
    noSlots: "Uygun saat yok",
    noDays: "Şu anda uygun saat yok",
    loading: "Yükleniyor...",
    yourDetails: "Bilgileriniz",
    nameLabel: "Ad",
    phoneLabel: "WhatsApp (alan koduyla)",
    emailLabel: "E-posta (isteğe bağlı)",
    requiredField: "Zorunlu alan",
    confirmBtn: "Randevuyu onayla",
    booking: "Randevu alınıyor...",
    back: "Geri",
    confirmedTitle: "Randevu onaylandı!",
    confirmedDesc: "Onayı WhatsApp'tan alacaksınız.",
    newBooking: "Başka randevu al",
    errSlot: "Bu saat artık uygun değil. Lütfen başka bir saat seçin.",
    errGeneric: "Tamamlanamadı. Lütfen tekrar deneyin.",
    minLabel: "dk",
    selectPlaceholder: "Seçin",
    notFound: "Randevu sayfası bulunamadı.",
    yourBooking: "Randevunuz",
    cancelBtn: "Randevuyu iptal et",
    rescheduleBtn: "Yeniden planla",
    cancelledMsg: "Randevunuz iptal edildi.",
    rescheduledMsg: "Randevu yeniden planlandı!",
    chooseNewTime: "Yeni bir saat seçin",
    cannotManage: "Bu randevu artık değiştirilemez.",
    confirmCancel: "İptal etmek istediğinizden emin misiniz?",
    chooseProfessional: "Bir uzman seçin",
    anyProfessional: "Herhangi biri",
    seatsLeft: "Yer: {n}"
  }
};

export function getBookingStrings(lang: BookingLang): BookingStrings {
  return STRINGS[lang] || STRINGS.pt;
}

/** Locale BCP-47 para Intl (datas/horas). */
export function intlLocale(lang: BookingLang): string {
  return lang === "pt" ? "pt-BR" : lang === "zh" ? "zh-CN" : lang;
}
